### ISSUE TITLE
[Fix] - Typo

### ISSUE THREAD

**Issue by vinisavordelli** [EricksonSiqueira/ericksonsiqueira.github.io#33]
Alterar:

Meu portfolio, onde falo um pouco sobre eu mesmo e as tecnolgias que conheço (esse site que você está utilizando)

Para:

Meu portfolio, onde falo um pouco sobre eu mesmo e as tecnologias que conheço (esse site que você está utilizando)

**Comment by EricksonSiqueira** [comment]
Corrigido! Muito obrigado pela contribuição Vini, salvou demais! 😄
